//! Generate one test per fixture directory.
//!
//! A single test looping over the cases would let the first failure hide the rest and would
//! make `cargo test crlf` unable to select one. Generating also removes the registration list
//! somebody eventually forgets to extend: a directory exists, therefore a test exists.

use std::path::Path;

fn main() {
    let fixtures = Path::new("tests/fixtures");
    println!("cargo:rerun-if-changed=tests/fixtures");

    let mut generated =
        String::from("// Generated by build.rs from tests/fixtures. Do not edit.\n");
    let mut count = 0;

    if let Ok(tools) = std::fs::read_dir(fixtures) {
        for tool in tools.flatten().filter(|e| e.path().is_dir()) {
            let tool_name = tool.file_name().to_string_lossy().into_owned();
            println!("cargo:rerun-if-changed=tests/fixtures/{tool_name}");
            let Ok(cases) = std::fs::read_dir(tool.path()) else {
                continue;
            };
            for case in cases.flatten().filter(|e| e.path().is_dir()) {
                let case_name = case.file_name().to_string_lossy().into_owned();
                let ident = format!("{}__{}", sanitise(&tool_name), sanitise(&case_name));
                generated.push_str(&format!(
                    "#[test]\nfn {ident}() {{ run_case(\"{tool_name}\", \"{case_name}\"); }}\n"
                ));
                count += 1;
            }
        }
    }
    // Whether any case exists is checked at run time in `fixture_hygiene`, not asserted here
    // against a number this file just computed: that would be true by construction.
    let _ = count;

    let out = std::path::PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    std::fs::write(out.join("golden_cases.rs"), generated).expect("write generated tests");
}

fn sanitise(name: &str) -> String {
    name.chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
        .collect()
}
